#!/bin/sh
cd $LAMBDA_TASK_ROOT
/opt/L42PortableLinux/L42Internals/jdk-16/bin/java \
    --enable-preview \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -cp /opt/l42-controller.jar \
    com.amazonaws.services.lambda.runtime.api.client.AWSLambda \
    l42client.Lambda
